### ISSUE TITLE
Projects.tsx - Display Error

### ISSUE THREAD

**Issue by OliverKarger** [OliverKarger/portfolio#1]
Project Items `<Project data={} />` are not displayed correctly. 
On my machine, the first and 9th Item are moved slightly down. 
No obvious reason.  

Related Code:
**pages/Projects.tsx**
```tsx
<main>
    <Navbar branding="Oliver Karger" />
    <h1 className={[css.page_header].join(" ")}>Project Overview</h1>
    <MDBContainer className={[css.projects].join(" ")}>
        {this.props.ghData.repositoryOwner.repositories.nodes.map(project => {
            return <Project data={project} />
        })}
    </MDBContainer>
</main>
```
**components/Project.tsx**
```tsx
export function Project(props: ProjectProps): JSX.Element {
    return (
        <MDBCol key={props.data.id} size="6" md="2" className={[css.project_col].join(" ")}>
            <h3 className={[css.project_header].join(" ")}> {props.data.name}</h3>
        </MDBCol >
    );
};
```

**styles/Project.module.scss*
```css
.page_header {
  text-align: center;
  margin: auto;
}

.project_col {
  border: 1px solid #1d1d1d;
  border-radius: 5px;
  display: inline-flex;
  padding: 0.5rem;
  margin: 1rem;
  min-height: 5rem;
  max-height: 15rem;
}

.project_header {
  text-align: center;
}
```

**styles/Projects.module.scss**
```css
.projects {
  height: auto;
  width: 100%;
  text-align: center;
  align-items: stretch;
}
```
