### ISSUE TITLE
Migrate vom SCSS to SASS

### ISSUE THREAD

**Issue by OliverKarger** [OliverKarger/portfolio#2]
**SCSS**
```scss
main {
 navbar {
  color: #fff;
 }
}
```
**SASS**
```sass
main
 navbar
  color #fff
```
